name: AudioPlayer
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
targets:
  AudioPlayer:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: AudioPlayer
    scheme: 
      testTargets: AudioPlayerTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.haruevorun.AudioPlayer"
      INFOPLIST_FILE: "AudioPlayer/Info.plist"
      SWIFT_VERSION: 5.0
      DEVELOPMENT_TEAM: "8446Z6F5D6"
    configFiles:
      Debug: configs/AudioPlayer-Debug.xcconfig
      Release: configs/AudioPlayer-Release.xcconfig
  AudioPlayerTests:
    platform: iOS
    type: bundle.unit-test
    configFiles:
      Debug: configs/AudioPlayerTests-Debug.xcconfig
    sources:
      - AudioPlayerTests/
    dependencies:
      - target: AudioPlayer
    scheme:
      testTargets:
        - AudioPlayerTests
      gatherCoverageData: true